### ISSUE TITLE
Running rspec includes all the stdout errors

### ISSUE THREAD

**Issue by tyler-ball** [chef-boneyard/chef-acceptance#20]
This makes it hard to see what tests are running, passing or failing.  We should capture all the stdout (or implement a real logging class that gets mocked) and only display it for a failing test

**Comment by patrick-wright** [comment]
@tyler-ball This is fixed now right?

**Comment by tyler-ball** [comment]
@patrick-wright I don't think so.  If I run `bundle exec rspec` I get this big chunk of output:

```
Encountered an error running the recipe provision: some error
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:149:in `block in and_raise'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:660:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:660:in `block in call'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:659:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:659:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:554:in `invoke_incrementing_actual_calls_by'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:411:in `invoke'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/proxy.rb:182:in `message_received'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/proxy.rb:321:in `message_received'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-mocks-3.4.1/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
/Users/tball/github/chef-acceptance/lib/chef-acceptance/application.rb:68:in `block in run_suite'
/Users/tball/github/chef-acceptance/lib/chef-acceptance/application.rb:66:in `each'
/Users/tball/github/chef-acceptance/lib/chef-acceptance/application.rb:66:in `run_suite'
/Users/tball/github/chef-acceptance/spec/chef-acceptance/application_spec.rb:105:in `block (6 levels) in <top (required)>'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/matchers/built_in/raise_error.rb:52:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/matchers/built_in/raise_error.rb:52:in `matches?'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:87:in `to'
/Users/tball/github/chef-acceptance/spec/chef-acceptance/application_spec.rb:105:in `block (5 levels) in <top (required)>'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:236:in `instance_exec'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:236:in `block in run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:478:in `block in with_around_and_singleton_context_hooks'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:435:in `block in with_around_example_hooks'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:478:in `block in run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/hooks.rb:478:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:435:in `with_around_example_hooks'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:478:in `with_around_and_singleton_context_hooks'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example.rb:233:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:581:in `block in run_examples'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:577:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:577:in `run_examples'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:543:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `block in run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `block in run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `block in run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/example_group.rb:544:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `map'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:118:in `block in run_specs'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/reporter.rb:77:in `report'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:117:in `run_specs'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:93:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/bin/rspec:23:in `load'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/bin/rspec:23:in `<main>'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/bin/ruby_executable_hooks:15:in `eval'
/Users/tball/.rvm/gems/ruby-2.1.6@chef-acceptance/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nandanhegde73** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
